[[section_builder_v2]]
arch = "x86_64"
git-tree-sha1 = "c543028382b6e7a4b2cdd5edf6464ccb2f9d72e7"
lazy = true
libc = "glibc"
os = "linux"

    [[section_builder_v2.download]]
    sha256 = "0ac821e7d4a831e1c865c630bac42960485ddac5f3a478205d32d13ea19d3b93"
    url = "https://github.com/runtosolve/section-builder-v2/releases/download/v0.0.1/section_builder_v2-x86_64-linux-gnu.tar.gz"
[[section_builder_v2]]
arch = "aarch64"
git-tree-sha1 = "855e5b1a3cea8381baa36534ad8dea09f0dab7de"
lazy = true
libc = "glibc"
os = "linux"

    [[section_builder_v2.download]]
    sha256 = "4ba38fb306c5e72155ffe8634dc66afe4a428bad27d2629775a41a7a6de41d85"
    url = "https://github.com/runtosolve/section-builder-v2/releases/download/v0.0.1/section_builder_v2-aarch64-linux-gnu.tar.gz"
[[section_builder_v2]]
arch = "aarch64"
git-tree-sha1 = "b2fbfccbc945553742bd068a29bfc16bb20577e1"
lazy = true
os = "macos"

    [[section_builder_v2.download]]
    sha256 = "c9f22b508950fc80bb20a329d7e357400880e5c43ccd46b6e2a328dfdabd0446"
    url = "https://github.com/runtosolve/section-builder-v2/releases/download/v0.0.1/section_builder_v2-aarch64-macos.tar.gz"
[[section_builder_v2]]
arch = "x86_64"
git-tree-sha1 = "4f05439bfcefe5ec7dfe0fb286258064bb02e7e7"
lazy = true
os = "windows"

    [[section_builder_v2.download]]
    sha256 = "181c359e379257b785ccee6e6416e70fb6103ee0226e24e59fb97a8e3ed46fd1"
    url = "https://github.com/runtosolve/section-builder-v2/releases/download/v0.0.1/section_builder_v2-x86_64-windows.tar.gz"
